### ISSUE TITLE
Failed to delete events

### ISSUE THREAD

**Issue by steve-qm** [eCrimeLabs/MISP-PurgeEvents#1]
Hi there,

Been on the look out for something like this for some time.  I've attempted to run the script although the deletion does not take place but fails instead.  I've ran the script without the --force as well which has the same results,  I have disabled the correlation which again has the same sort of results.  Any advise would be much appreciated.

Also tried with a smaller event count with the same results.

MISP Currently installed version… v2.4.159 (10b21ba3819254d4c70ed751e246d84fdf8cfd0c)

# venv/bin/python misp-purgeevents.py -f 2010-01-01 -l 2022-04-04 -v --force
eCrimeLabs MISP Purge Events tool v.0.1
 - Find all events for deletion between: 2010-01-01 and 2022-04-04
 - 26 fixed events for exclusion from Feeds
  - Searching events in MISP between 2010-01-01 and 2022-04-04
  - 37 events excluded based on OrgC UUID's
  - Excluded OrgC UUID(s):
   + OrgC UUID: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  - 68894 events identified and up for deletion, splitting into chunks of 400
    - Result: 0 event(s) deleted, and 400 Failed
    - Result: 0 event(s) deleted, and 400 Failed
    - Result: 0 event(s) deleted, and 400 Failed
    - Result: 0 event(s) deleted, and 400 Failed
    - Result: 0 event(s) deleted, and 400 Failed
    - Result: 0 event(s) deleted, and 400 Failed
    - Result: 0 event(s) deleted, and 400 Failed
	...
	...
	...
    - Result: 0 event(s) deleted, and 400 Failed
    - Result: 0 event(s) deleted, and 400 Failed
    - Result: 0 event(s) deleted, and 400 Failed
    - Result: 0 event(s) deleted, and 400 Failed
    - Result: 0 event(s) deleted, and 400 Failed
    - Result: 0 event(s) deleted, and 94 Failed
  - Summarized Result: 0 events deleted, and 68894 Failed
 ------------------------------------------
 - Purge Completed

**Comment by eCrimeLabs** [comment]
Hey there, 

You should try to look at and ensure that the user or API key is not set to read-only.

To test you can also when logged into MISP access: https://<MISP URL>/api/rest

HTTP Method to use: POST
Relative path to query: /events/delete
Check "Show result"
HTTP Headers:
```
Authorization: YOUR_API_KEY 
Accept: application/json
Content-type: application/json
```
HTTP Body:
```
{
    "id": "<INSERT ID>"
}
```

**Comment by steve-qm** [comment]
{ "saved": false, "name": "Could not delete Event", "message": "Could not delete Event", "url": "/events/delete", "errors": "Event was not deleted." }

this is the response,  I have confirmed the API key does not have read-only as well so should have the correct permissions.


It seems that the correct path is /events/delete/(EventID) with DELETE method.

as /events/delete  with the Event ID in the body does not delete the event.

**Comment by eCrimeLabs** [comment]
Hey there,

I've until now not been able to replicate this issue, is there any additional information you can share 
- Role of User
- Version of Python

As I can see form the original post the search and exclusions seems to go as planned so it is the deletion, any data from the weblogs that could point in a direction ?

**Comment by steve-qm** [comment]
Hello,

User role is admin with python3.8

I've deployed a fresh misp in another environment also experiencing the same issue which is quite strange.

`

misp@misp:~/MISP-PurgeEvents$
misp@misp:~/MISP-PurgeEvents$
misp@misp:~/MISP-PurgeEvents$ venv/bin/python misp-purgeevents.py -f 2010-01-01 -l 2022-07-07 -d
eCrimeLabs MISP Purge Events tool v.0.1
 - Running in dryrun mode (NO DATA WILL BE DELETED)
 - Find all events for deletion between: 2010-01-01 and 2022-07-07
/home/misp/MISP-PurgeEvents/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to                                                                               host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/misp/MISP-PurgeEvents/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to                                                                               host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/misp/MISP-PurgeEvents/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to                                                                               host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/misp/MISP-PurgeEvents/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to                                                                               host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
  - Searching events in MISP between 2010-01-01 and 2022-07-07
/home/misp/MISP-PurgeEvents/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to                                                                               host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
  - 0 events excluded based on OrgC UUID's
  - 1 events identified and up for deletion
------------------------------------------
- Simulated Purge Completed
misp@misp:~/MISP-PurgeEvents$
misp@misp:~/MISP-PurgeEvents$
misp@misp:~/MISP-PurgeEvents$
misp@misp:~/MISP-PurgeEvents$
misp@misp:~/MISP-PurgeEvents$ venv/bin/python misp-purgeevents.py -f 2010-01-01 -l 2022-07-07
eCrimeLabs MISP Purge Events tool v.0.1
 - Find all events for deletion between: 2010-01-01 and 2022-07-07
 - Continue data deletion in MISP (answer: YES to continue)?y
/home/misp/MISP-PurgeEvents/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to                                                                               host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/misp/MISP-PurgeEvents/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to                                                                               host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/misp/MISP-PurgeEvents/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to                                                                               host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
/home/misp/MISP-PurgeEvents/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to                                                                               host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
  - Searching events in MISP between 2010-01-01 and 2022-07-07
/home/misp/MISP-PurgeEvents/venv/lib/python3.8/site-packages/urllib3/connectionpool.py:1043: InsecureRequestWarning: Unverified HTTPS request is being made to                                                                               host 'localhost'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
  - 1 events identified and up for deletion
    - Sleeping 360 seconds - To give database time to recover and cleanup - Failed attempts
  - Summarized Result: 0 events deleted, and 1 Failed
 ------------------------------------------
 - Purge Completed
misp@misp:~/MISP-PurgeEvents$ 

`

**Comment by xdjibi** [comment]
Likely related to the POST request for deletion that fails due to TLS/SSL certificate check.
Submitted a Pull Request to fix it : https://github.com/eCrimeLabs/MISP-PurgeEvents/pull/2
